[fix] Prevent loading from empty `src` in `Avatar` component
snehilvj/dash-mantine-components pull request #372
Opened 2024-10-24 22:30 UTC by mmarfat

### Summary
This PR addresses an issue in the `Avatar` component where the component attempts to load a resource even when no `src` is provided. Previously, when `src` was missing or empty, it led to a `GET about:blank net::ERR_UNKNOWN_URL_SCHEME` error.

![avatar](https://github.com/user-attachments/assets/9848fdf0-f3b7-41dc-9f4f-32275f4d9768)

If `src` is empty or undefined, the component should not attempt to load an image. By adding this check, the component behaves more gracefully and avoids errors related to invalid URL schemes.

### Changes
- Updated the `sanitizedSrc` to return `undefined` when `src` is not provided.

### Example
```
import dash_mantine_components as dmc
from dash import Dash, html, _dash_renderer

_dash_renderer._set_react_version("18.2.0")

app = Dash()

avatars = [
    dmc.Avatar(src="https://avatars.githubusercontent.com/u/91216500?v=4"),
    dmc.Avatar("MK"), # This shouldn't output errors into the console
    dmc.Avatar(src="https://avatars.githubusercontent.com/u/91216500?v=4", children="MK")
]

app.layout = dmc.MantineProvider(
    html.Div(avatars)
)

if __name__ == '__main__':
    app.run_server(debug=True)
```

Let me know if you have any feedback or if you run into issues.

2024-10-24 22:41 UTC, AnnMarieW commented
Hi @mmarfat 

This looks really good - Thanks!

Would you like to convert your example into a test?  You can find an example here https://github.com/snehilvj/dash-mantine-components/blob/master/tests/test_popover.py

The test for this PR would be even simpler because there are no callbacks needed.  
This line checks for errors in the console

```
 assert dash_duo.get_logs() == []
```

2024-10-25 07:40 UTC, mmarfat commented
Hi @AnnMarieW 

I've added the test but I was having some issues with `pytest` so I can't be 100% sure it passes. However, it seems simple enough so I believe it should work.

2024-10-25 13:39 UTC, AnnMarieW requested changes
Hi @mmarfat 

This is a good start.  It just needs to make sure the component is rendered before checking for console errors.

2024-10-25 13:39 UTC, AnnMarieW commented on tests/test_avatar.py
> +    avatar = dmc.Avatar("MK")
```suggestion
    avatar = dmc.Avatar("MK", id="avatar")

```

2024-10-25 13:39 UTC, AnnMarieW commented on tests/test_avatar.py
> +
```suggestion

    # Wait for the app to load
    dash_duo.wait_for_text_to_equal("#avatar", "MK")

```

2024-10-25 13:54 UTC, mmarfat commented
Ok, thanks. I've committed the reviewed changes.

2024-10-25 14:03 UTC, AnnMarieW commented
Great!  Looks good :slightly_smiling_face: 

Could you also please add an entry to the [CHANGELOG.md](https://github.com/snehilvj/dash-mantine-components/blob/master/CHANGELOG.md).  
Under  Unreleased, add a Fixed section and include a short description, a reference to this PR and your GitHub username.

2024-10-25 14:19 UTC, mmarfat commented
Done. I'll try to remember to do it next time without having to be reminded 😅.

2024-10-25 14:26 UTC, AnnMarieW approved these changes

2024-10-25 18:23 UTC, alexcjohnson approved these changes

2024-10-25 18:24 UTC, merged

2024-10-25 18:25 UTC, AnnMarieW commented
This was a nice catch - Thanks again @mmarfat :pray: